//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlabafw.DB_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medlabaEntities : DbContext
    {
        public medlabaEntities()
            : base("name=medlabaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Анализ> Анализ { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<ПараметрыАнализов> ПараметрыАнализов { get; set; }
        public virtual DbSet<Пациент> Пациент { get; set; }
        public virtual DbSet<РезультатАнализа> РезультатАнализа { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<ТипАнализа> ТипАнализа { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
