//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlabafw.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Анализ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Анализ()
        {
            this.РезультатАнализа1 = new HashSet<РезультатАнализа>();
        }
    
        public int КодАнализа { get; set; }
        public System.DateTime ДатаСдачи { get; set; }
        public int КодТипа { get; set; }
        public string Пациент { get; set; }
        public int РезультатАнализа { get; set; }
        public string АнализПроводил { get; set; }
    
        public virtual Пациент Пациент1 { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual ТипАнализа ТипАнализа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатАнализа> РезультатАнализа1 { get; set; }
    }
}
