//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlabafw.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПараметрыАнализов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПараметрыАнализов()
        {
            this.РезультатАнализа = new HashSet<РезультатАнализа>();
        }
    
        public int КодПараметра { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public int ПринадлежитТипу { get; set; }
    
        public virtual ТипАнализа ТипАнализа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатАнализа> РезультатАнализа { get; set; }
    }
}
